version: "3.6"
services:
    web:
        build: .
        volumes:
            - .:/app
        ports:
            - 8000:8000
        tty: true
    db:
        image: mysql:8
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: 'laravel'
            MYSQL_PASSWORD: 'root'
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - laravel-db:/var/lib/mysql

volumes:
    laravel-db:
